### ISSUE TITLE
Markdown extended als Möglichkeit Schlagwörter, Tags, Kategorien umzusetzen

### ISSUE THREAD

**Issue by hfanieng** [NADOOIT/NADOO-Wiki#418]
Aktuell wären 126 README.md-Dateien in .mdx umzubenennen und die Links anzupassen.

Vorteil: GitHub parst die .mdx Dateien und kann mit Tags arbeiten.

**Comment by hfanieng** [comment]
---
title: Teil 1 der gestreckten Abschlussprüfung (GAP)

description: Eine Übersicht über die erste Hälfte der gestreckten Abschlussprüfung (GAP) in der Ausbildung zum Fachinformatiker für Anwendungsentwicklung.
pubDate: 2025-03-25

categories:
  - AP1
  - "2025"
  - März
  - Frühjahr

tags:
  - IT-Prozesse
  - Kl-gestützte Software
  - Kundenanfragen
  - Kundenanliegen
  - Kundenstörungen
  - Künstliche Intelligenz
  - Meldung
  - Netzwerküberwachung
  - Sicherheit
  - Wartung
---

**Comment by hfanieng** [comment]
# Markdown Extended

Ja, .mdx mit Frontmatter ist eine sehr gute Alternative – besonders wenn du strukturierte Inhalte, Tags und Filterbarkeit brauchst, ohne auf GitHub-Wiki oder Labels zurückzugreifen.

---

✅ Vorteile von .mdx mit Frontmatter

**Vorteil - Beschreibung ***

🏷 Tags & Metadaten - Du kannst Tags, Kategorien, Autoren u.v.m. in der Frontmatter definieren (YAML-Block oben).
🧠 Filterbar & auslesbar - Tools wie Astro, Next.js, Docusaurus oder ein Custom Parser können diese Frontmatter maschinell auswerten.
🔍 Volle Kontrolle - Keine GitHub-Suchlimitierung, du baust dein eigenes System für Suche, Filter, Sortierung etc.
🌐 Kompatibel mit Static Site Generators -Perfekt kombinierbar mit Astro, Eleventy, Hugo oder Next.js für eine moderne Dokumentation.
📄 MDX = Markdown + Komponenten: Du kannst React-Komponenten einbetten und z. B. TagBadge, DocWarning etc. verwenden.
🔄 Versionierbar - Du kannst die .mdx-Dateien in deinem Git-Repo versionieren und so Änderungen nachverfolgen

---

🧪 Beispiel .mdx mit Frontmatter

```mdx
---
title: "Code-Review bei GitHub"
tags: [github, code-review, workflow]
author: "Heiko"
date: "2025-05-07"
---
```

```tsx
import TagBadge from '@/components/TagBadge'
```

## Code-Review

```tsx
<TagBadge tag="code-review" />
```

Ein Code-Review ist die Überprüfung von Code durch andere Teammitglieder...

---

🔧 Was du dafür brauchst

- Ein Build-System (z. B. Astro, Docusaurus, Next.js)
- Frontmatter-Parser (z. B. gray-matter, bei Astro integriert)
- Tag-Komponente oder Seitenlogik, um nach Tags zu filtern oder aufzulisten

---

📌 Fazit

.mdx mit Frontmatter ist eine professionelle, zukunftssichere Lösung, wenn:

- du die Inhalte versionieren möchtest,
- GitHub-intern eingeschränkt suchbar ist,
- du langfristig eine Doku-Plattform aufbauen willst, z. B. mit Astro oder Next.js.

**Comment by hfanieng** [comment]
# Struktur für MDS-Projekte

Ja, absolut sinnvoll! Bei 200+ Tags und mehreren Aufgaben pro Thema ist es besser, Inhalte und Aufgaben strikt zu trennen – sowohl organisatorisch als auch technisch. Damit wird dein Wiki:

- übersichtlich und skalierbar
- pflegeleicht (je Thema 1 Ort)
- leicht automatisierbar (z. B. Suche, Aufgabenverlinkung)

---

## Empfohlene Projektstruktur

```plaintext
/docs
├── 09-katalog
│   ├── ap1
│   │   ├── projektmanagement
│   │   │   └── README.mdx
│   │   ├── wirtschaftlichkeit
│   │   │   └── README.mdx
│   │   └── ...
│   ├── ap2
│   │   ├── versionsverwaltung
│   │   │   └── README.mdx
│   │   ├── programmierung
│   │   │   └── README.mdx
│   │   └── ...
│   └── bwl-recht-sicherheit
│       ├── arbeitsrecht
│       │   └── README.mdx
│       └── datenschutz
│           └── README.mdx

├── 10-aufgaben
│   ├── ap1
│   │   ├── projektmanagement
│   │   │   ├── aufgabe-1.mdx
│   │   │   ├── aufgabe-2.mdx
│   │   │   └── aufgabe-3.mdx
│   ├── ap2
│   │   ├── versionsverwaltung
│   │   │   ├── aufgabe-1.mdx
│   │   │   ├── aufgabe-2.mdx
│   │   │   └── aufgabe-3.mdx
│   └── bwl-recht-sicherheit
│       └── datenschutz
│           ├── aufgabe-1.mdx
│           ├── aufgabe-2.mdx
│           └── aufgabe-3.mdx
```

---

## 📋 Vorteile

| Punkt | Erklärung |
| :--- | :--- |
| Klar getrennt | Theorie (/09-katalog) und Praxis (/10-aufgaben) |
| Skalierbar | Du kannst pro Tag/Thema beliebig viele Aufgaben oder Varianten anlegen |
| Wiederverwendbar | Aufgaben lassen sich unabhängig versionieren oder referenzieren |
| Tagbasiert | Du kannst die Aufgaben mit frontmatter automatisch auf Thema mappen |
| Filterbar & sortierbar | Z. B. via difficulty, tag, ap, category etc. |

---

## 🧪 Beispiel aufgabe-1.mdx mit Frontmatter

```mdx
---
title: "Versionskontrolle mit Git – Branching"
relatedTo: "versionsverwaltung"
ap: "ap2"
tags: [git, branching, versionierung]
difficulty: "mittel"
aufgabentyp: "verständnisfrage"
---
```

---

## 👉 Empfehlung

- Führe /09-katalog/ für alle Wissensinhalte nach Prüfungskatalog
- Führe /10-aufgaben/ für prüfungsnahe Aufgaben je Thema.
- Nutze ein zentrales Mapping via relatedTo in der frontmatter, um automatisiert Aufgaben im Thema anzuzeigen oder zu verlinken.

**Comment by hfanieng** [comment]
```bash
#!/bin/bash

# Basisverzeichnisse
KATALOG_DIR="docs/09-katalog"
AUFGABEN_DIR="docs/10-aufgaben"

# Beispielhafte Liste deiner Tags als Datei oder direkt hier im Array (kann ersetzt werden durch Datei-Input)
TAGS=(
  "ap1/projektmanagement"
  "ap1/wirtschaftlichkeit"
  "ap2/versionsverwaltung"
  "ap2/programmierung"
  "bwl-recht-sicherheit/datenschutz"
)

# Anzahl Aufgaben pro Thema
AUFGABEN_COUNT=3

# Funktion: Erstelle Struktur
for TAG in "${TAGS[@]}"; do
  # Ordnerpfade ableiten
  THEMA_PATH_KAT="$KATALOG_DIR/$TAG"
  THEMA_PATH_TASK="$AUFGABEN_DIR/$TAG"

  # Ordner erstellen
  mkdir -p "$THEMA_PATH_KAT"
  mkdir -p "$THEMA_PATH_TASK"

  # README.mdx im Katalog, wenn nicht vorhanden
  if [ ! -f "$THEMA_PATH_KAT/README.mdx" ]; then
    cat <<EOF > "$THEMA_PATH_KAT/README.mdx"
---
title: "$(basename "$TAG" | sed 's/-/ /g' | sed 's/^./\U&/')"
tags: [$(basename "$TAG")]
ap: ["$(echo $TAG | cut -d'/' -f1)"]
category: "$(basename "$TAG")"
draft: true
---

<!-- Inhalt zum Thema $(basename "$TAG") -->
EOF
  fi

  # Aufgaben erzeugen
  for i in $(seq 1 $AUFGABEN_COUNT); do
    cat <<EOF > "$THEMA_PATH_TASK/aufgabe-$i.mdx"
---
title: "Aufgabe $i zu $(basename "$TAG")"
relatedTo: "$(basename "$TAG")"
ap: "$(echo $TAG | cut -d'/' -f1)"
tags: [$(basename "$TAG")]
difficulty: "mittel"
aufgabentyp: "offen"
draft: true
---

<!-- Aufgabe $i zum Thema $(basename "$TAG") -->
EOF
  done

done

echo "Struktur für Katalog + Aufgaben erfolgreich erstellt."
```

**Comment by hfanieng** [comment]
```yaml
name: Convert Issues with Frontmatter to MDX

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  convert-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Issue Content
        id: extract
        run: |
          echo "TITLE<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '[.[] | .name] | join(",")')" >> $GITHUB_ENV
          echo "AUTHOR=${{ github.event.issue.user.login }}" >> $GITHUB_ENV
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Generate File Path and Content
        run: |
          # Parse tag and AP from labels (you can customize this logic)
          TAG=$(echo "$LABELS" | cut -d',' -f1)
          AP=$(echo "$LABELS" | grep -o 'ap[12]' || echo "ap2")

          # Convert tag to folder-friendly path
          DEST_PATH="docs/09-katalog/$AP/$TAG"
          FILE_NAME="README-${ISSUE_NUMBER}.mdx"

          mkdir -p "$DEST_PATH"

          # Create MDX file
          cat <<EOF > "$DEST_PATH/$FILE_NAME"
---
title: "$TITLE"
tags: [${TAG}]
ap: ["${AP}"]
author: "$AUTHOR"
date: "$(date +'%Y-%m-%d')"
draft: false
---

$BODY
EOF

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add docs/
          git commit -m "Auto-create MDX for issue #$ISSUE_NUMBER ($TAG)"
          git push
```
